apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      run: my-web
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: my-web
    spec:
      containers:
      - name: my-web-container
        image: aa04726/my_registry:ex-web4
        ports:
        - containerPort: 80
